# Generated by Django 4.0.dev20210907095959 on 2021-10-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0002_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trello_app.task_list'),
            preserve_default=False,
        ),
    ]
