# Generated by Django 4.0.dev20210907095959 on 2021-11-02 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0003_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 5, 57, 34, 341642, tzinfo=utc)),
        ),
    ]
